# Generated by Django 6.0.2 on 2026-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=150)),
                ('employeeDepartment', models.CharField(max_length=150)),
                ('employeeYear', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('employeeType', models.CharField(max_length=150)),
            ],
        ),
    ]
