# Generated by Django 6.0.2 on 2026-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=150)),
                ('phoneNumber', models.IntegerField()),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
