# Generated by Django 6.0.2 on 2026-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=150)),
                ('studentDepartment', models.CharField(max_length=150)),
                ('studentYear', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('studentType', models.CharField(max_length=150)),
            ],
        ),
    ]
